name: Deploy to the Server

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Install sshpass
    #   run: sudo apt-get install -y sshpass

    - name: Pull latest changes from GitHub
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@premium188.web-hosting.com -p21098 << 'EOF'
        cd /home/zizimnnf/princeak
        git pull https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/princeak8/princeak.git main
        EOF

    - name: Run post-deployment scripts
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@premium188.web-hosting.com -p21098 << 'EOF'
        cd /home/zizimnnf/princeak

        # Run migrations for the main database
        php artisan migrate --force

        # Seed The data
        php artisan db:seed --class=DatabaseSeeder

        # Install Composer dependencies
        composer install --no-dev --optimize-autoloader

        # Clear various caches
        php artisan route:clear
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear

        nvm use 20.19.2
        npm install
        npm run build

        # Create Request Docs
        # php artisan laravel-request-docs:export

        EOF
